# Generated by Django 5.1.15 on 2026-06-07 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hp', models.PositiveIntegerField(default=30)),
                ('start_attack', models.PositiveIntegerField(default=8)),
                ('start_defense', models.PositiveIntegerField(default=4)),
                ('start_gold', models.PositiveIntegerField(default=20)),
                ('grid_size', models.PositiveIntegerField(default=10)),
                ('monster_count', models.PositiveIntegerField(default=6)),
                ('treasure_count', models.PositiveIntegerField(default=3)),
                ('xp_base', models.PositiveIntegerField(default=50)),
                ('xp_growth', models.FloatField(default=1.5)),
                ('stat_growth', models.PositiveIntegerField(default=3)),
                ('rest_cost', models.PositiveIntegerField(default=10)),
                ('treasure_gold_min', models.PositiveIntegerField(default=5)),
                ('treasure_gold_max', models.PositiveIntegerField(default=25)),
            ],
            options={
                'verbose_name': 'Game config',
                'verbose_name_plural': 'Game config',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable id, e.g. 'iron-sword'", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('consumable', 'Consumable'), ('weapon', 'Weapon'), ('armor', 'Armor')], max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('heal', models.PositiveIntegerField(default=0, help_text='HP restored (consumables)')),
                ('attack_bonus', models.PositiveIntegerField(default=0, help_text='When equipped (weapons)')),
                ('defense_bonus', models.PositiveIntegerField(default=0, help_text='When equipped (armor)')),
                ('sellable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('max_hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('gold_reward', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('min_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PluginState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('max_hp', models.PositiveIntegerField(default=30)),
                ('hp', models.PositiveIntegerField(default=30)),
                ('base_attack', models.PositiveIntegerField(default=8)),
                ('base_defense', models.PositiveIntegerField(default=4)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('map_seed', models.BigIntegerField(default=0)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('cleared', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('slot', models.CharField(blank=True, max_length=20, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark-fantasy', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
