# Generated by Django 5.1.15 on 2026-06-07 15:14
from django.db import migrations, models

# Extra monsters for variety, so encounters feel less repetitive.
NEW_MONSTERS = [
    # key, name, hp, atk, def, gold, xp, min_level
    ("bat", "Cave Bat", 6, 4, 0, 4, 6, 1),
    ("skeleton", "Skeleton", 16, 7, 3, 12, 18, 2),
    ("bandit", "Bandit", 22, 10, 3, 20, 26, 3),
    ("orc", "Orc", 30, 12, 4, 28, 36, 4),
]


def populate(apps, schema_editor):
    Monster = apps.get_model("game", "Monster")
    for key, name, hp, atk, dfn, gold, xp, min_level in NEW_MONSTERS:
        Monster.objects.update_or_create(
            key=key,
            defaults=dict(name=name, max_hp=hp, attack=atk, defense=dfn,
                          gold_reward=gold, xp_reward=xp, min_level=min_level),
        )
    # Bump the existing single config row to the richer, denser map values.
    GameConfig = apps.get_model("game", "GameConfig")
    cfg, _ = GameConfig.objects.get_or_create(pk=1)
    cfg.grid_size = 12
    cfg.monster_count = 14
    cfg.treasure_count = 6
    cfg.save()


def depopulate(apps, schema_editor):
    Monster = apps.get_model("game", "Monster")
    Monster.objects.filter(key__in=[m[0] for m in NEW_MONSTERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_seed_plugin_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='grid_size',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='monster_count',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='treasure_count',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.RunPython(populate, depopulate),
    ]
