# Generated by Django 5.1.15 on 2026-06-07 15:26

from django.db import migrations, models

# Default sprites from the Kenney Tiny Dungeon pack (CC0).
ITEM_ICONS = {
    "potion": "tile_0115",        # red flask
    "iron-sword": "tile_0105",    # sword
    "leather-armor": "tile_0056", # shield (defense)
    "example-charm": "tile_0114", # green flask (from template plugin, if present)
}
MONSTER_ICONS = {
    "slime": "tile_0108",
    "goblin": "tile_0124",
    "wolf": "tile_0122",
    "bat": "tile_0120",
    "skeleton": "tile_0121",
    "bandit": "tile_0087",
    "orc": "tile_0109",
}


def set_icons(apps, schema_editor):
    Item = apps.get_model("game", "Item")
    Monster = apps.get_model("game", "Monster")
    for key, icon in ITEM_ICONS.items():
        Item.objects.filter(key=key).update(icon=icon)
    for key, icon in MONSTER_ICONS.items():
        Monster.objects.filter(key=key).update(icon=icon)


def clear_icons(apps, schema_editor):
    apps.get_model("game", "Item").objects.update(icon="")
    apps.get_model("game", "Monster").objects.update(icon="")


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameconfig_grid_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, help_text="Sprite name in static/sprites, e.g. 'tile_0115'", max_length=40),
        ),
        migrations.AddField(
            model_name='monster',
            name='icon',
            field=models.CharField(blank=True, help_text="Sprite name in static/sprites, e.g. 'tile_0108'", max_length=40),
        ),
        migrations.RunPython(set_icons, clear_icons),
    ]
