# Generated by Django 5.1.15 on 2026-06-08 00:16

from django.db import migrations, models


def tune(apps, schema_editor):
    GameConfig = apps.get_model("game", "GameConfig")
    cfg, _ = GameConfig.objects.get_or_create(pk=1)
    cfg.encounter_rate = 0.18   # ~1 battle every 5-6 steps
    cfg.treasure_count = 5
    cfg.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rogue_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='encounter_rate',
            field=models.FloatField(default=0.18, help_text='Chance (0-1) of a random battle per step on grass'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='treasure_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.RunPython(tune, noop),
    ]
