# Generated by Django 5.1.15 on 2026-06-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameconfig_encounter_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable id, e.g. 'lumber-camp'", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('production', 'Production'), ('storage', 'Storage'), ('progression', 'Progression'), ('military', 'Military'), ('defense', 'Defense')], default='production', max_length=20)),
                ('footprint_w', models.PositiveIntegerField(default=1)),
                ('footprint_h', models.PositiveIntegerField(default=1)),
                ('cost_wood', models.PositiveIntegerField(default=0)),
                ('cost_stone', models.PositiveIntegerField(default=0)),
                ('cost_growth', models.FloatField(default=1.6, help_text='Cost multiplier per level')),
                ('build_seconds', models.PositiveIntegerField(default=5, help_text='Build time at level 1')),
                ('build_growth', models.FloatField(default=1.7, help_text='Build-time multiplier per level')),
                ('produces', models.CharField(blank=True, choices=[('', 'None'), ('wood', 'Wood'), ('stone', 'Stone'), ('meat', 'Meat')], default='', max_length=10)),
                ('production_rate', models.PositiveIntegerField(default=0, help_text='Units/min at level 1')),
                ('storage_bonus', models.PositiveIntegerField(default=0, help_text='Added to resource cap, per level')),
                ('max_level', models.PositiveIntegerField(default=5)),
                ('requires_longhouse_level', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(blank=True, help_text="Sprite name in static/sprites, e.g. 'tile_0058'", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.PositiveIntegerField(default=0)),
                ('stone', models.PositiveIntegerField(default=0)),
                ('meat', models.PositiveIntegerField(default=0)),
                ('last_tick', models.DateTimeField(auto_now_add=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='village', to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('build_finish_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.buildingtype')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.village')),
            ],
        ),
    ]
