# Generated by Django 5.1.15 on 2026-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_seed_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='max_counts',
            field=models.JSONField(blank=True, default=dict, help_text='How many you may own, by Longhouse level. e.g. {"1": 1, "3": 2, "5": 3} = 1 at LH1, 2 at LH3, 3 at LH5.'),
        ),
    ]
