# Generated by Django 5.1.15 on 2026-06-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_seed_build_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable id, e.g. 'greenwood'", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('biome', models.CharField(choices=[('grass', 'Grass / Forest'), ('desert', 'Desert / Sand'), ('ice', 'Ice'), ('dungeon', 'Dungeon / Mine'), ('city', 'City')], default='grass', max_length=20)),
                ('seed', models.BigIntegerField(default=1, help_text='Layout seed for surface areas')),
                ('size', models.PositiveIntegerField(default=12)),
                ('is_start', models.BooleanField(default=False, help_text='Where new characters begin')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='area_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monster',
            name='biome',
            field=models.CharField(blank=True, help_text='Restrict spawns to this biome (blank = any)', max_length=20),
        ),
        migrations.AddField(
            model_name='monster',
            name='sight_radius',
            field=models.PositiveIntegerField(default=4, help_text='How far (tiles) it spots and chases the player'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_here', to='game.maparea'),
        ),
        migrations.CreateModel(
            name='MapConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('door', 'Door'), ('mine', 'Mine entrance'), ('hole', 'Hole with stairs'), ('stairs', 'Stairs'), ('portal', 'Portal'), ('town', 'To town (menu)')], default='door', max_length=20)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('descend', models.BooleanField(default=False, help_text='Generate a fresh level on use (dungeon depth)')),
                ('from_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='game.maparea')),
                ('to_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='game.maparea')),
            ],
        ),
    ]
