# Generated by Django 5.1.15 on 2026-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_seed_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='category',
            field=models.CharField(choices=[('production', 'Production'), ('storage', 'Storage'), ('progression', 'Progression'), ('service', 'Service'), ('military', 'Military'), ('defense', 'Defense')], default='production', max_length=20),
        ),
    ]
