# Generated by Django 5.1.15 on 2026-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_seed_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='emoji',
            field=models.CharField(blank=True, help_text="Emoji shown on the map/grid, e.g. '🔨' (preferred over icon)", max_length=8),
        ),
        migrations.AddField(
            model_name='monster',
            name='emoji',
            field=models.CharField(blank=True, help_text="Emoji shown on the map/combat, e.g. '🐺' (preferred over icon)", max_length=8),
        ),
    ]
