# Generated by Django 5.1.15 on 2026-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_castle_village_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='iron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='produces',
            field=models.CharField(blank=True, choices=[('', 'None'), ('wood', 'Wood'), ('stone', 'Stone'), ('meat', 'Meat'), ('iron', 'Iron')], default='', max_length=10),
        ),
    ]
