# Generated by Django 5.1.15 on 2026-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_seed_mine'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='refine_level',
            field=models.PositiveIntegerField(default=0, help_text='Smithy +level'),
        ),
    ]
