# Generated by Django 5.1.15 on 2026-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_inventoryitem_refine_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(blank=True, choices=[('weapon', 'Weapon'), ('shield', 'Shield'), ('helmet', 'Helmet'), ('armor', 'Armor'), ('boots', 'Boots'), ('amulet', 'Amulet')], help_text='Equipment slot (gear only; blank for consumables)', max_length=20),
        ),
    ]
