# Generated by Django 5.1.15 on 2026-06-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_seed_desert_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='recovering_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='troops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapconnection',
            name='kind',
            field=models.CharField(choices=[('door', 'Door'), ('mine', 'Mine entrance'), ('hole', 'Hole with stairs'), ('stairs', 'Stairs'), ('portal', 'Portal'), ('town', 'Town gate (🏠)')], default='door', max_length=20),
        ),
    ]
