# Generated by Django 5.1.15 on 2026-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_plain_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='travel_arrive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='travel_dest_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='maparea',
            name='world_x',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='maparea',
            name='world_y',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
